from typing import Any

class MemoryPool:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def malloc(self, size: int) -> Any: ...
    def free_all_blocks(self) -> Any: ...
    def used_bytes(self) -> int: ...
    def total_bytes(self) -> int: ...

class UnownedMemory:
    def __init__(self, ptr: int, size: int, owner: Any) -> None: ...

class MemoryPointer:
    def __init__(self, memory: UnownedMemory, offset: int) -> None: ...

class _Runtime:
    def getDeviceCount(self) -> int: ...
    def setDevice(self, device_id: int) -> Any: ...
    def getDeviceProperties(self, device_id: int) -> dict[str, Any]: ...
    def runtimeGetVersion(self) -> int: ...
    def driverGetVersion(self) -> int: ...
    def malloc(self, size: int) -> int: ...
    def free(self, ptr: int) -> Any: ...
    def memcpy(self, destination: int, source: int, size: int, kind: int) -> Any: ...
    def memset(self, ptr: int, value: int, size: int) -> Any: ...
    def deviceSynchronize(self) -> Any: ...

runtime: _Runtime
